In [12]:
#Імпортуємо потрібну бібліотеку
import pandas as pd

In [13]:
#Завантажуємо файли з результатами і з переліком запитань
df= pd.read_csv('results.csv', low_memory=False)
df_schema= pd.read_csv('schema.csv', low_memory=False)

Завдання 1. Підрахунок загальної кількості респондентів

In [14]:
#Визначаємо загальну кількість респондентів, які взяли участь в опитуванні
total_respondents = df['ResponseId'].nunique()
print(f"Всього респондентів: ", total_respondents)

Всього респондентів:  49191

Завдання 2. Аналіз повноти відповідей респондентів

In [15]:
#Створюємо множину унікальних запитань із таблиці schema з їхнім переліком
questions = set(df_schema['qname'].unique())

In [18]:
#Робимо перетин множини запитань із файлу з запитаннями і відповідей за 2025 рік. 
#Записуємо результат у комірку common_questions
common_questions = list(questions.intersection(df.columns))

In [19]:
#Створюємо таблицю на основі первинної таблиці з відповідями. Залишаємо лише ті стовпчики, у яких немає пропусків
df_clean = df.dropna(subset=common_questions)

In [9]:
#Виводимо результати підрахунку стовпчиків без пропусків 
print(f"Кількість респондентів, які дали відповіді на всі запитання: ", df_clean.shape[0])

Кількість респондентів, які дали відповіді на всі запитання:  0

In [10]:
#Висновок: Жодний із респондентів не відповів на всі питання.

Завдання 3. Статистичний аналіз досвіду респондентів

In [21]:
#Подивимося, скільки респондентів не відповіли на питання щодо досвіду роботи або мають досвід менше 6 місяців
missing_exp = df['WorkExp'].isna().sum()
print(f"Пропущених значень у стовпці досвіду роботи: {missing_exp}")

Пропущених значень у стовпці досвіду роботи: 6298

In [22]:
#Приберемо ці рядки з таблиці, щоб не викривлювати результати обчислення мір центральної тенденції
clean_exp = df.dropna(subset=['WorkExp'])

In [23]:
#Підраховуємо окремо середнє, медіану і моду у первинній таблиці, виводимо результати через f-рядок.

mean = df ['WorkExp'].mean()
median = df ['WorkExp'].median()
mode= df ['WorkExp'].mode()

print(f"Досвід роботи респондентів у роках (таблиця з пропусками)\nСереднє значення:  {mean.round()} \nМедіана:  {median} \nМода:  {mode[0]}")

Досвід роботи респондентів у роках (таблиця з пропусками)
Середнє значення:  13.0
Медіана:  10.0
Мода:  10.0

In [24]:
#Підраховуємо окремо середнє, медіану і моду у таблиці без пропусків, виводимо результати через f-рядок.

mean = clean_exp ['WorkExp'].mean()
median = clean_exp ['WorkExp'].median()
mode= clean_exp ['WorkExp'].mode()

print(f"Досвід роботи респондентів у роках (таблиця без пропусків)\nСереднє значення:  {mean.round()} \nМедіана:  {median} \nМода:  {mode[0]}")

Досвід роботи респондентів у роках (таблиця без пропусків)
Середнє значення:  13.0
Медіана:  10.0
Мода:  10.0

In [ ]:
#Значення за обома таблицями не відрізняються.
#Це свідчить про те, що респонденти з будь-яким досвідом роботи не давали відповідь на це питання однаково часто.

Завдання 4. Аналіз віддаленої роботи

In [25]:
#Підраховуємо, яку кількість разів у стовпчику RemoteWork зустрічається слово Remote
#Використовуємо саме таке написання, оскільки серед відповідей зустрічається змішаний варіант,
#який передбачає віддалену + очну роботу (там слово remote вжито з маленької букви)
#Неправильне написання виключено, оскільки респонденти обирали серед запропонованих варіантів відповідей.

print(f"Кількість віддалених працівників: ", df['RemoteWork'].value_counts()["Remote"])

Кількість віддалених працівників:  10931

Завдання 5. Визначення популярності Python

In [26]:
#Шукаємо колонку з мовами програмування за ключовим словом Language
print([col for col in df.columns if 'Language' in col])

['LanguageChoice', 'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired', 'LanguagesHaveEntry', 'LanguagesWantEntry']

In [27]:
#Виявилося багато таких колонок. Треба визначити, яка з них підходить для нашого завдання. 
#Перечитаємо запитання із таблиці зі списком питань
pd.set_option('display.max_colwidth', None)
language_questions = df_schema.loc[df_schema['question'].str.contains('language', case=False)]
language_questions

,qid,qname,question,type,sub,sq_id
55,QID10,LearnCodeChoose,Did you begin learning to code or learn a new coding skill/programming language in the last year?,MC,NaN,NaN
75,QID44,LanguageChoice,"Did you work with programming, scripting and markup languages in the last year or do you plan to in the year to come? Here, we are referring to anything you use that is conventionally referred to as code.",MC,NaN,NaN
76,QID34,Language,"Which <b>programming, scripting, and markup languages</b> have you done extensive development work in over the past year, and which do you want to work in over the next year? (If you both worked with the language and want to continue to do so, please check both boxes in that row.)",Matrix,NaN,NaN
77,QID51,LanguagesHaveEntry,"Was the programming language you use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you used in the past year</strong>.",TE,NaN,NaN
78,QID52,LanguagesWantEntry,"Was the programming language you want to use not listed above? List below, separated by a comma and a space for each, the programming language(s) <strong>you want to use next year</strong>.",TE,NaN,NaN
105,QID50,AIModelsChoice,"Did you utilize or integrate specific Large Language Models (LLMs) to power your development tools or applications in the last year? Here, we are referring to models like GPT-4, Llama, Claude, etc., within your development environments or solutions.",MC,NaN,NaN

In [28]:
#Подивившись у pdf-файлі на те, як поставлено запитання щодо мови програмування, 
#бачимо, що нам підходить стовпчик LanguageHaveWorkedWith
#Оскільки серед варіантів мов є MicroPython, використовуємо для пошуку чисто Пайтона вираз r\bPython\b
df['is_python'] = df['LanguageHaveWorkedWith'].str.contains(r"\bPython\b", na=False, regex=True) 

#Оцінимо, чи правильно заповнена колонка is_python
df[['LanguageHaveWorkedWith', 'is_python']].head(10)

,LanguageHaveWorkedWith,is_python
0,Bash/Shell (all shells);Dart;SQL,False
1,Java,False
2,Dart;HTML/CSS;JavaScript;TypeScript,False
3,Java;Kotlin;SQL,False
4,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;PowerShell;Python;SQL;TypeScript;VBA;Visual Basic (.Net),True
5,Java;Scala,False
6,JavaScript;TypeScript,False
7,Bash/Shell (all shells);HTML/CSS;JavaScript;Python;SQL;TypeScript,True
8,Java;Python;Scala,True
9,NaN,False

In [29]:
#Рахуємо кількість респондентів, які використовують Пайтон
pyhton_true = df['is_python'].sum() 
print(f"Всього використовують Пайтон ", pyhton_true, "користувачів")

Всього використовують Пайтон  18410 користувачів

In [31]:
#Підраховуємо відсоток користувачів Пайтона серед усіх респондентів, округлюємо до десятих.
python_users_percentage = pyhton_true/total_respondents * 100
print (f"Частка Python-розробників серед усіх респондентів: ", python_users_percentage.round(1),"%")

Частка Python-розробників серед усіх респондентів:  37.4 %

Завдання 6. Аналіз шляхів навчання програмуванню

In [124]:
#Створюємо нову колонку, як у попередньому завданні.
#У стовпці LearnCode шукаємо словосполучення Online Courses. 
#Якщо таке є, додаємо у нову колонку True. Якщо немає або NA - False.

df['is_online_courses'] = df['LearnCode'].str.contains("Online Courses", na=False)

In [34]:
#Рахуємо кількість респондентів, які навчалися коду на онлайн-курсах
online_courses_true = df['is_online_courses'].sum() 
print(f"Навчалися на онлайн-курсах ", online_courses_true, "користувачів")

Навчалися на онлайн-курсах  10973 користувачів

Завдання 7. Географічний аналіз компенсації Python-розробників

In [43]:
#Створюємо нову таблицю, куди потраплять тільки ті респонденти, які програмують на Пайтоні. 
#Щоб не займати багато пам'яті, беремо лише стовпці з зарплатою та країною. 
python_devs = df.loc[df['is_python']==True, ['Country', 'ConvertedCompYearly']].copy()

In [50]:
#Видаляємо рядки, у яких не вказано компенсацію
python_devs_clean = python_devs.dropna(subset=['ConvertedCompYearly'])

                     Country  ConvertedCompYearly
4                    Ukraine              60000.0
7                    Ukraine              72000.0
8                    Ukraine              70000.0
22  United States of America              87500.0
27                    Sweden             209643.0

In [59]:
#Групуємо за країною і розраховуємо середню та медіанну зарплати по країнах.
python_devs_agg = python_devs_clean.groupby('Country')['ConvertedCompYearly'].agg(['mean', 'median']).round()

In [60]:
python_devs_agg

                                          mean    median
Country
Afghanistan                            22329.0    1000.0
Albania                                59018.0   58890.0
Algeria                                20187.0    7088.0
Andorra                               226104.0  226104.0
Antigua and Barbuda                        1.0       1.0
...                                        ...       ...
Venezuela, Bolivarian Republic of...    9909.0    3000.0
Viet Nam                              218837.0    8254.0
Yemen                                  32930.0   23672.0
Zambia                                  5424.0    3206.0
Zimbabwe                               34000.0   25500.0

[153 rows x 2 columns]

Завдання 8. Аналіз освіти найбільш оплачуваних спеціалістів

In [73]:
#Створюємо таблицю з колонками зарплати й освіти.
best_paid_devs = df[['ResponseId', 'ConvertedCompYearly', 'EdLevel']].sort_values(by='ConvertedCompYearly', ascending=False).reset_index(drop = True)

In [74]:
best_paid_devs.head()

,ResponseId,ConvertedCompYearly,EdLevel
0,34268,50000000.0,"Associate degree (A.A., A.S., etc.)"
1,28701,33552715.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"
2,43144,18387548.0,"Associate degree (A.A., A.S., etc.)"
3,35354,15430267.0,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)"
4,45972,13921760.0,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)"

In [ ]:
#Всі найбільш оплачувані працівники мають той чи інший ступінь вищої освіти.

*Завдання 9. Аналіз популярності Python по віковим категоріям

In [96]:
#Перевіримо, чи немає пропущених значень у стовпчику Age
df['Age'].isna().any()

np.False_

In [ ]:
#Пропущених рядків немає

In [89]:
#Створимо маски, які відображатимуть кількість респондентів за віковими групами
python_by_age = df[df['is_python']==True].groupby('Age')['ResponseId'].count()
python_by_age

Age
18-24 years old      3678
25-34 years old      6082
35-44 years old      4849
45-54 years old      2413
55-64 years old       976
65 years or older     295
Prefer not to say     117
Name: ResponseId, dtype: int64

In [90]:
all_by_age = df.groupby('Age')['ResponseId'].count()
all_by_age

Age
18-24 years old       9210
25-34 years old      16519
35-44 years old      13241
45-54 years old       6275
55-64 years old       2626
65 years or older      942
Prefer not to say      378
Name: ResponseId, dtype: int64

In [101]:
#Підрахуємо відсоток користувачів Пайтона за віковими групами, округлимо до сотих
python_percentage_by_age = (python_by_age / all_by_age *100).round (2).reset_index()
python_percentage_by_age

                 Age  ResponseId
0    18-24 years old       39.93
1    25-34 years old       36.82
2    35-44 years old       36.62
3    45-54 years old       38.45
4    55-64 years old       37.17
5  65 years or older       31.32
6  Prefer not to say       30.95

In [103]:
#Замінюємо назву стовпців для більш зрозумілого представлення
python_percentage_by_age.columns = ['Age category', 'Python percentage (%)']
python_percentage_by_age

        Age category  Python percentage (%)
0    18-24 years old                  39.93
1    25-34 years old                  36.82
2    35-44 years old                  36.62
3    45-54 years old                  38.45
4    55-64 years old                  37.17
5  65 years or older                  31.32
6  Prefer not to say                  30.95

In [ ]:
#У всіх вікових категоріях відсоток користувачів Пайтона у межах від 30 до 40%.

Завдання 10. Аналіз індустрій серед високооплачуваних віддалених працівників

In [108]:
#Залишимо тільки потрібні нам колонки
df10 = df [['ResponseId', 'Industry', 'ConvertedCompYearly', 'RemoteWork']]

,ResponseId,Industry,ConvertedCompYearly,RemoteWork
0,1,Fintech,61256.0,Remote
1,2,Retail and Consumer Services,104413.0,"Hybrid (some in-person, leans heavy to flexibility)"
2,3,Software Development,53061.0,NaN
3,4,Retail and Consumer Services,36197.0,Remote
4,5,Software Development,60000.0,NaN
...,...,...,...,...
49186,49187,NaN,NaN,NaN
49187,49188,NaN,NaN,NaN
49188,49189,Banking/Financial Services,NaN,"Hybrid (some in-person, leans heavy to flexibility)"
49189,49190,NaN,NaN,NaN
49190,49191,NaN,NaN,NaN

In [112]:
#Приберемо рядки, які мають пусті значення
df10_clean = df10.dropna().reset_index(drop=True)

,ResponseId,Industry,ConvertedCompYearly,RemoteWork
0,1,Fintech,61256.0,Remote
1,2,Retail and Consumer Services,104413.0,"Hybrid (some in-person, leans heavy to flexibility)"
2,4,Retail and Consumer Services,36197.0,Remote
3,8,Software Development,72000.0,Remote
4,9,Banking/Financial Services,70000.0,Remote
...,...,...,...,...
21056,49099,Software Development,2729.0,In-person
21057,49106,Software Development,719.0,In-person
21058,49107,Software Development,69008.0,"Hybrid (some in-person, leans heavy to flexibility)"
21059,49122,Manufacturing,58007.0,"Hybrid (some remote, leans heavy to in-person)"
21060,49123,Software Development,46406.0,"Your choice (very flexible, you can come in when you want or just as needed)"

In [115]:
#Визначимо користувачів, які входять до 25% тих, хто заробляє більше решти
top_25 = df10_clean['ConvertedCompYearly'].quantile(0.75)
#Створимо маски для фільтрації даних за зарплатою та віддаленою роботою
top_25_devs = df10_clean['ConvertedCompYearly'] > top_25
remote_devs = df10_clean['RemoteWork'].str.contains("Remote")

In [123]:
#Порахуємо кількість віддалених працівників у кожній сфері та упорядкуємо дані за найбільш поширеною сферою
best_paid_remote_industry = df10_clean [top_25_devs & remote_devs].groupby('Industry').size().sort_values(ascending=False)
best_paid_remote_industry

Industry
Software Development                          1174
Fintech                                        188
Healthcare                                     186
Other:                                         176
Internet, Telecomm or Information Services     137
Banking/Financial Services                      87
Government                                      78
Media & Advertising Services                    75
Retail and Consumer Services                    65
Transportation, or Supply Chain                 63
Computer Systems Design and Services            59
Insurance                                       46
Energy                                          45
Manufacturing                                   33
Higher Education                                29
dtype: int64

In [ ]:
#З великим відривом (на порядок) лідирує розробка програмного забезпечення.